#!/usr/bin/env bash

source "$PLUGIN_AVAILABLE_PATH/dscribe/functions"

APP_NAME=$2

fn-has-app-name "$APP_NAME"

dokku apps:create "${APP_NAME}api"
dokku apps:create "${APP_NAME}api-staging"
dokku apps:create "${APP_NAME}api-sprint"

dokku dscribe:packenv "${APP_NAME}api"

slackurl=`dokku dscribe:slack prod`
test ! -z "$slackurl" && dokku slack:set "${APP_NAME}api" "$slackurl"

slackurl=`dokku dscribe:slack sprint`
test ! -z "$slackurl" && dokku slack:set "${APP_NAME}api-staging" "$slackurl"
test ! -z "$slackurl" && dokku slack:set "${APP_NAME}api-sprint" "$slackurl"
